openapi: 3.0.1
info:
  title: User API
  version: 1.0.0
servers:
  - url: 'https://174.129.53.222:8080/'
  - url: 'https://delta-12-kbin-8d30caa623a4.herokuapp.com'
paths:
  /u/{id}:
    get:
      summary: Get User Profile
      security:
      - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: Update User Profile
      security:
      - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: User profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /u/{id}/articles:
    get:
      summary: Get User Articles
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User articles retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'

  /u/{id}/comments:
    get:
      summary: Get User Comments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User comments retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'

  /u/{id}/boosts:
    get:
      summary: Get User Boosts
      security:
      - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User boosts retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Boost'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /u/{id}/deleteAvatar:
    patch:
      summary: Delete User Avatar
      security:
      - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User avatar deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /u/{id}/deleteBack:
    patch:
      summary: Delete User Background
      security:
      - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User background deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        full_name:
          type: string
        description:
          type: string
        avatar:
          type: string
        background:
          type: string

    UserUpdate:
      type: object
      properties:
        user:
          type: object
          properties:
            full_name:
              type: string
            description:
              type: string
            avatar:
              type: string
            background:
              type: string

    Article:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string

    Comment:
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        created_at:
          type: string
          format: date-time

    Boost:
      type: object
      properties:
        id:
          type: integer
        amount:
          type: number
          format: float
        created_at:
          type: string
          format: date-time

    Message:
      type: object
      properties:
        message:
          type: string

    Error:
      type: object
      properties:
        status:
          type: string
        error:
          type: string
          
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
